"""add pipeline_stage and pipeline_stage_status to documents

Revision ID: 3e02c6964bfd
Revises: 09_add_embedding_search_vector
Create Date: 2026-08-17 07:49:45.339652

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3e02c6964bfd'
down_revision: Union[str, Sequence[str], None] = '09_add_embedding_search_vector'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('pipeline_stage', sa.Enum('EXTRACT', 'CHUNK', 'EMBED', 'OCR', 'CAPTION_FIGURES', 'DEDUPE', name='pipelinestage', native_enum=False), nullable=True))
    op.add_column('documents', sa.Column('pipeline_stage_status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'SKIPPED', name='pipelinestagestatus', native_enum=False), nullable=False, server_default='QUEUED'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'pipeline_stage_status')
    op.drop_column('documents', 'pipeline_stage')
    # ### end Alembic commands ###
